version: '3'
services:
  http:
    image: nginx
    volumes:
      - ./tests/resources/:/usr/share/nginx/html/
    ports:
      - 9000:80
  dali:
    image: ${RUNTIME_IMAGE:-ghcr.io/olxgroup-oss/dali/dali}:${RUNTIME_TAG:-latest}
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
    environment:
      - RUN_MODE=compose
